### ISSUE TITLE
WIP: Assert actual matches expected using dynamic assertions

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#1]
Assertions in a workflow are valuable, especially in workflows for validating the behaviour of an action. There's a fantastic action [Assert Action](https://github.com/marketplace/actions/assert-action) _however_ it is limited to a fixed set of string based assertions.

- [x] A Workflow can include custom assertions defined in the repository
- [x] `expected`, `actual`

```yaml
- uses: pr-mpt/actions-assert
  with: 
    expected: "Hello, World!"
    actual: "${{ steps.message.outputs.greeting }}"
    assertion: "is-equal"
    type: boolean|string|int|json
    each: true # should we iterate through a new line delimited list
```

# Features

- [x] Configurable type (integer, boolean, string)
- [x] Accepts external assertions from npm packages and the repository
- [x] Results include messages

# Assertions

- [ ] Pattern match https://github.com/pr-mpt/assertions/issues/6
- [ ] Status code (cURL) https://github.com/pr-mpt/assertions/issues/7

# Questions

- [x] ~An assertion might have more complex configuration, how do we provide that? Some sort of hacky nested json driven with for config? e.g: an http request might require a bearer token~ -> environment variables
