### ISSUE TITLE
Document usage of `continue-on-error` for pipeline usage

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#24]
A pipeline might derive value from the result of `passed` (e.g: checking if a `dist` directory exists in order to allow a tag to be created). The [`continue-on-error`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) option enables this use-case.

```yaml
- id: dist
  continue-on-error: true
  uses: pr-mpt/actions-assert@v2.0.0-alpha
  with:
    assertion: "npm://@assertions/directory-exists"
    actual: "dist"
```
