### ISSUE TITLE
Accept a list of multiple `expected` inputs to be individually tested

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#3]
GitHub Actions parameters (`with`) are transferred through environment variables and received by the action as string values, so it is not possible to provide a list of values in yaml format. However, we _can_ accept multi-line strings and assume that each new line is a new input -- taking advantage of `valueOfInput` to get each input as the right type.

There are valid multi-line single value inputs though so it cannot be default behaviour. An `each` option that instructs the action to split by new lines and perform the assertion on each value is a helpful middle-ground.

```yaml
inputs:
  each:
    description: "Test each line in a multi-line `expected` as a unique input"
    default: false
```

```yaml
- uses: pr-mpt/actions-assert
  with: 
    type: number
    each: true
    actual: |
      2
      4
    assertion: is-even-number
```

```
pass: true
2 is an even number
pass: true
4 is an even number
```
