### ISSUE TITLE
Source javascript assertions from npm packages

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#4]
Assertions are just javascript so they could be distributed via npm. An installed package exists on the local file system so _technically_ it's possible by constructing a path to the dependency (e.g: `../node_modules/@pr-mpt/assert-is-today/dist/index.js`) but it's a little unwieldy -- a user must first identify the dist location, then construct the path. 

A shortcut that can be prefixed to an assertion name to instruct the package to identify the assertion location would make this much easier for users, e.g:

```yaml
- uses: pr-mpt/actions-assert
  with: 
    assertion: "npm:@pr-mpt/assert-is-today"
    # ...
```

- [ ] A project might not use Javascript: does encouraging the use of `package.json` make sense? Maybe they should live exclusively in the Workflow: does an action exist for installing npm packages in a Workflow? e.g:
- [ ] This package could be responsible for installing them?

```yaml
- uses: hypothetical/actions-install-npm-package
  with:
    packages: @pr-mpt/assert-is-today
- uses: pr-mpt/actions-assert
  with: 
    assertion: "npm:@pr-mpt/assert-is-today"
    # ...
```
