### ISSUE TITLE
Add `failed` output as inverse of `passed`

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#44]
A Workflow may choose _not_ to fail if the assertion does not pass (see: #42) and then perform some further steps depending on the result. Although `passed` can be used, it does require that the condition explicitly compares the _value_ of passed, so `failed` output will simplify the conditions.

before:

```yaml
- id: example
  uses: pr-mpt/actions-assert@v2
  with:
    assertion: npm://@assertions/is-equal
    expected: "Hello, World!"
    actual: "Goodbye, World!"
    fail: true
- if: ${{ steps.example.outputs.passed != 'true' }}
  run: echo "Assertion failed"
```

after:

```yaml
- id: example
  uses: pr-mpt/actions-assert@v2
  with:
    assertion: npm://@assertions/is-equal
    expected: "Hello, World!"
    actual: "Goodbye, World!"
    fail: true
- if: steps.example.outputs.failed
  run: echo "Assertion failed"
```

ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
