### ISSUE TITLE
Add version parameter to `npm://` assertions

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-assert#50]
The [`live-plugin-manager`](https://www.npmjs.com/package/live-plugin-manager) package accepts a version parameter.

- [x] Parse version from assertion name using `<package>:<version>` format
- [x] Replace all examples with explicit version reference to encourage safe usage
- [x] Default to `v1` _not_ `latest` for safety and to address #49?

```yaml
- name: Test actor is @shrink
  uses: pr-mpt/actions-assert@v2
  with:
    assertion: npm://@assertions/is-equal@v1
    actual: "${{ github.actor }}"
    expected: shrink
```
